# RVPN Client configuration

pre_shared_key="3e0f85e0f68e241b1b52d2c5429bf41a6c85845b6f0aa7b8c8d905723f917cc6"

server="192.168.88.253:9000"

[interface]
    address="10.42.0.2/24"
    addresses=["fd42::2/64"]
    mode="tun"
    mtu=1400
    name="rvpn-client0"

[routing]
    # Route IPv4 and IPv6 Internet traffic through the RVPN server.
    default_route=true
    default_route_v6=true

    endpoint_gateway="192.168.88.253"

    # VPN gateways.
    gateway="10.42.0.1"
    gateway_v6="fd42::1"

[auth]
    local_identity_seed="75bebfbed1ec1fd3130aeb03b377300767eb19658ab0349f7b7de3f3a27f78a2"
    mode="pinned-key"
    peer_public_key="092bf3b225421ebeb53fc14cae391ae15b567fcf6fe8aa3e58b95e6f570f8713"
