[package]
    authors.workspace=true
    edition.workspace=true
    license.workspace=true
    name="rvpn-tray"
    version.workspace=true

[dependencies]
    anyhow.workspace=true
    bytes.workspace=true
    caps="0.5.6"
    libc.workspace=true
    rvpn-config={path="../../crates/rvpn-config"}
    rvpn-core={path="../../crates/rvpn-core"}
    rvpn-ipc={path="../../crates/rvpn-ipc"}
    tao="0.37.0"
    tokio.workspace=true
    tracing.workspace=true
    tracing-subscriber.workspace=true
    tray-icon={version="0.25.0", default-features=false, features=["ksni"]}
