# RVPN Client configuration for 'ShowNex' (generated)

obfuscation_key="cc8a4e6e1af2fbe6d77330c68a4fe6edcb08da4585fd549058b8230f59aae914"
server="192.168.88.254:9000"

[interface]
    address="10.42.0.4/24"
    addresses=["fd42::4/64"]
    dns_servers="192.168.88.1"
    mode="tun"
    mtu=1400
    name="rvpn-android-shownex"

[routing]
    default_route=true
    default_route_v6=true
    endpoint_gateway="192.168.88.254:9000"
    gateway="10.42.0.1"
    gateway_v6="fd42::1"

[auth]
    local_identity_seed="3775368fcd6141ad0dddd085a5d30910fe45f0cfb989aecca04e88016c3a039d"
    mode="pinned-key"
    peer_public_key="070bec56ad3302f92b9f52b9ca36e186c525a12a244ecb20b67a85cd3f64066c"

[handshake]
    retry_interval_ms=150
    retry_limit=5

[rekey]
    packet_limit=1000000
