[project]
name = "builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Frank1o3", email = "jahdy1o3@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "cryptography>=50.0.1",
    "segno>=1.6.6",
]

[project.scripts]
builder = "builder:cli.main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
